import { Source_Sans_3} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const ss = Source_Sans_3({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // Customize weights
  display: "swap",
});

export const metadata = {
  title: "CRE-calcy - Chemical Engineering Calculator",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.jpg", // This sets favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ss.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
